# Generated by Django 3.2.8 on 2021-10-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='nom',
            new_name='nompre',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='prenom',
        ),
    ]
