# Generated by Django 3.2.8 on 2021-10-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20211029_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='classe',
        ),
    ]
