# Generated by Django 3.2.8 on 2021-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0006_auto_20211103_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='classe',
        ),
        migrations.AddField(
            model_name='note',
            name='classes',
            field=models.ManyToManyField(to='bulletin.Classe'),
        ),
    ]
