# Generated by Django 3.2.8 on 2021-11-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0008_auto_20211103_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='eleves',
        ),
        migrations.AddField(
            model_name='note',
            name='eleves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletin.eleve'),
        ),
    ]
