# Generated by Django 3.2.8 on 2021-11-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_auto_20211103_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='matieres',
        ),
        migrations.AddField(
            model_name='note',
            name='matieres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletin.matiere'),
        ),
    ]
