# Generated by Django 3.2.8 on 2021-11-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0010_auto_20211103_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='classe',
        ),
    ]
