# Generated by Django 3.2.8 on 2021-11-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0012_note_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='classe',
            new_name='classes',
        ),
    ]
