# Generated by Django 3.2.8 on 2021-11-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0013_rename_classe_note_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='name',
            field=models.CharField(max_length=190, null=True, unique=True),
        ),
    ]
