# Generated by Django 3.2.8 on 2022-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0015_auto_20211127_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='date1',
            field=models.DateTimeField(null=True),
        ),
    ]
