# Generated by Django 3.2.8 on 2022-01-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0016_matiere_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='date1',
        ),
    ]
